# Generated by Django 5.1.4 on 2024-12-21 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='image',
            field=models.ImageField(default='chais/', upload_to='chais/'),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='name',
            field=models.CharField(default='MASALA', max_length=100),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='type',
            field=models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KL', 'KIWI'), ('PL', 'PLAIN'), ('EL', 'ELAICHI')], default='ML', max_length=2),
        ),
    ]
